### ISSUE TITLE
Stack deployment parameters.

### ISSUE THREAD

**Issue by SeraPayFinTech** [scunning1987/ads_reference_server#1]
Hey, could you include the stack deployment parameters for the template, 

I'm getting a memory error.

**Comment by scunning1987** [comment]
Hey, 
Thanks for bringing the issue to my attention. I've resolved the issue with the CloudFormation template.

The stack deployment fails as key files are copied to an S3 bucket using a custom resource. The Lambda code for the custom resource tries to copy to S3 with ACL='public-read', which will fail if the bucket is not labelled as public.

If you're having memory issues in the Lambda "VASTProcessor", then you can modify the 'MemorySize' on line 113 of the CloudFormation template to be a lower value. 10240 is the current maximum supported value in Lambda.
